# 01 · Data Collection
Fetches NBA game logs and Genius lyrics metadata for all 110 mentions.

**Run time:** ~15–25 minutes (API rate limits).

Prerequisites:
```
pip install -r requirements.txt
cp .env.example .env  # then add your GENIUS_API_KEY
```

In [1]:
import sys
sys.path.insert(0, '..')
from src.fetch_gamelogs import fetch_all as fetch_games
from src.fetch_lyrics import fetch_all as fetch_lyrics
import pandas as pd

mentions = pd.read_csv('../data/raw/mentions.csv')
print(f"Loaded {len(mentions)} mentions across {mentions['player'].nunique()} unique players")
mentions.head()

Loaded 160 mentions across 92 unique players

,mention_id,player,player_id_bref,artist,song,album,release_date,mention_type,lyric,artist_tier,player_position,era
0,1,LeBron James,jamesle01,Drake,Forever,Relapse: Refill,2009-08-13,compliment,That's why they call me Young Money LeBron Jam...,2.8,SF,2000s
1,2,Kobe Bryant,bryanko01,Lil Wayne,Kobe Bryant,No Ceilings,2009-11-16,compliment,Call me Kobe Bryant cause I'm ballin' every night,2.5,SG,2000s
2,3,Shaquille O'Neal,onealsh01,Notorious B.I.G.,The What,Ready to Die,1994-09-13,compliment,I'm catchin' bodies like Shaq catch alley-oops,3.0,C,1990s
3,4,Allen Iverson,iversal01,Jay-Z,Hovi Baby,The Dynasty: Roc La Familia,2000-10-31,compliment,Flow butter smooth like Iverson crossover,3.0,PG,2000s
4,5,Kevin Durant,duranke01,Kendrick Lamar,Backseat Freestyle,good kid m.A.A.d city,2012-10-22,neutral,Got K.D. numbers scoring every night,2.9,SF,2010s

In [2]:
# Fetch NBA game logs (nba_api)
# This hits NBA's API — be patient, it takes a few minutes
# Already-fetched players are skipped automatically
fetch_games('../data/raw/mentions.csv')

Fetching game logs for 92 unique players...

  0%|                                                                                           | 0/92 [00:00<?, ?it/s]

  → Fetching LeBron James (9 seasons)...
  ✓ 679 games for LeBron James

  1%|▉                                                                                  | 1/92 [00:08<12:32,  8.27s/it]

  → Fetching Kobe Bryant (7 seasons)...
  ✓ 530 games for Kobe Bryant

  2%|█▊                                                                                 | 2/92 [00:16<12:17,  8.19s/it]

  → Fetching Shaquille O'Neal (7 seasons)...
  ✓ 510 games for Shaquille O'Neal

  3%|██▋                                                                                | 3/92 [00:24<12:14,  8.25s/it]

  → Fetching Allen Iverson (8 seasons)...
  ✓ 535 games for Allen Iverson

  4%|███▌                                                                               | 4/92 [00:33<12:10,  8.30s/it]

  → Fetching Kevin Durant (7 seasons)...
  ✓ 457 games for Kevin Durant

  5%|████▌                                                                              | 5/92 [00:40<11:33,  7.97s/it]

  → Fetching Patrick Ewing (5 seasons)...
  ✓ 393 games for Patrick Ewing

  7%|█████▍                                                                             | 6/92 [00:48<11:30,  8.03s/it]

  → Fetching Michael Jordan (3 seasons)...
  ✓ 82 games for Michael Jordan

  8%|██████▎                                                                            | 7/92 [00:52<09:39,  6.82s/it]

  → Fetching Gary Payton (5 seasons)...
  ✓ 409 games for Gary Payton

  9%|███████▏                                                                           | 8/92 [01:06<12:31,  8.94s/it]

  → Fetching Vince Carter (3 seasons)...
  ✓ 207 games for Vince Carter

 10%|████████                                                                           | 9/92 [01:09<10:02,  7.25s/it]

  → Fetching Tim Duncan (6 seasons)...
  ✓ 453 games for Tim Duncan

 11%|████████▉                                                                         | 10/92 [01:17<09:54,  7.25s/it]

  → Fetching Dwyane Wade (7 seasons)...
  ✓ 457 games for Dwyane Wade

 12%|█████████▊                                                                        | 11/92 [01:24<09:50,  7.29s/it]

  → Fetching Chris Paul (5 seasons)...
  ✓ 333 games for Chris Paul

 13%|██████████▋                                                                       | 12/92 [01:29<08:56,  6.71s/it]

  → Fetching Kevin Garnett (7 seasons)...
  ✓ 548 games for Kevin Garnett

 14%|███████████▌                                                                      | 13/92 [01:59<17:48, 13.52s/it]

  → Fetching James Harden (5 seasons)...
  ✓ 394 games for James Harden

 15%|████████████▍                                                                     | 14/92 [02:04<14:26, 11.11s/it]

  → Fetching Stephen Curry (8 seasons)...
  ✓ 540 games for Stephen Curry

 16%|█████████████▎                                                                    | 15/92 [02:13<13:14, 10.32s/it]

  → Fetching Kyrie Irving (6 seasons)...
  ✓ 398 games for Kyrie Irving

 17%|██████████████▎                                                                   | 16/92 [02:20<11:43,  9.26s/it]

  → Fetching Giannis Antetokounmpo (4 seasons)...
  ✓ 307 games for Giannis Antetokounmpo

 18%|███████████████▏                                                                  | 17/92 [02:24<09:47,  7.83s/it]

  → Fetching Luka Doncic (3 seasons)...
  ✗ Could not find NBA API ID for: Luka Doncic
  ✗ No data for Luka Doncic

 20%|████████████████                                                                  | 18/92 [02:24<06:54,  5.60s/it]

  → Fetching Ja Morant (4 seasons)...
  ✓ 248 games for Ja Morant

 21%|████████████████▉                                                                 | 19/92 [02:29<06:21,  5.22s/it]

  → Fetching Dwight Howard (3 seasons)...
  ✓ 239 games for Dwight Howard

 22%|█████████████████▊                                                                | 20/92 [02:32<05:37,  4.68s/it]

  → Fetching Russell Westbrook (5 seasons)...
  ✓ 354 games for Russell Westbrook

 23%|██████████████████▋                                                               | 21/92 [02:56<12:20, 10.43s/it]

  → Fetching Carmelo Anthony (9 seasons)...
  ✓ 369 games for Carmelo Anthony

 24%|███████████████████▌                                                              | 22/92 [03:11<13:52, 11.89s/it]

  → Fetching Derrick Rose (5 seasons)...
  ✓ 208 games for Derrick Rose

 25%|████████████████████▌                                                             | 23/92 [03:17<11:27,  9.96s/it]

  → Fetching Baron Davis (3 seasons)...
  ✓ 163 games for Baron Davis

 26%|█████████████████████▍                                                            | 24/92 [03:20<09:07,  8.05s/it]

  → Fetching Penny Hardaway (3 seasons)...
  ✓ 218 games for Penny Hardaway

 27%|██████████████████████▎                                                           | 25/92 [03:25<07:41,  6.89s/it]

  → Fetching Stephon Marbury (3 seasons)...
  ✓ 230 games for Stephon Marbury

 28%|███████████████████████▏                                                          | 26/92 [03:29<06:44,  6.13s/it]

  → Fetching Tracy McGrady (3 seasons)...
  ✓ 172 games for Tracy McGrady

 29%|████████████████████████                                                          | 27/92 [03:48<10:44,  9.91s/it]

  → Fetching Paul Pierce (3 seasons)...
  ✓ 241 games for Paul Pierce

 30%|████████████████████████▉                                                         | 28/92 [03:51<08:28,  7.95s/it]

  → Fetching Yao Ming (3 seasons)...
  ✓ 219 games for Yao Ming

 32%|█████████████████████████▊                                                        | 29/92 [03:55<06:58,  6.64s/it]

  → Fetching Jason Kidd (3 seasons)...
  ✓ 226 games for Jason Kidd

 33%|██████████████████████████▋                                                       | 30/92 [03:58<05:52,  5.69s/it]

  → Fetching Steve Nash (3 seasons)...
  ✓ 231 games for Steve Nash

 34%|███████████████████████████▋                                                      | 31/92 [04:02<05:05,  5.01s/it]

  → Fetching Dirk Nowitzki (3 seasons)...
  ✓ 239 games for Dirk Nowitzki

 35%|████████████████████████████▌                                                     | 32/92 [04:05<04:35,  4.59s/it]

  → Fetching Ray Allen (3 seasons)...
  ✓ 201 games for Ray Allen

 36%|█████████████████████████████▍                                                    | 33/92 [04:09<04:15,  4.33s/it]

  → Fetching Amare Stoudemire (3 seasons)...
  ✓ 217 games for Amare Stoudemire

 37%|██████████████████████████████▎                                                   | 34/92 [04:15<04:37,  4.78s/it]

  → Fetching Chauncey Billups (3 seasons)...
  ✓ 234 games for Chauncey Billups

 38%|███████████████████████████████▏                                                  | 35/92 [04:20<04:44,  4.99s/it]

  → Fetching Gilbert Arenas (3 seasons)...
  ✓ 89 games for Gilbert Arenas

 39%|████████████████████████████████                                                  | 36/92 [04:24<04:12,  4.51s/it]

  → Fetching Paul George (7 seasons)...
  ✓ 446 games for Paul George

 40%|████████████████████████████████▉                                                 | 37/92 [04:32<05:16,  5.75s/it]

  → Fetching Kawhi Leonard (4 seasons)...
  ✓ 215 games for Kawhi Leonard

 41%|█████████████████████████████████▊                                                | 38/92 [04:37<04:47,  5.33s/it]

  → Fetching Joel Embiid (4 seasons)...
  ✓ 229 games for Joel Embiid

 42%|██████████████████████████████████▊                                               | 39/92 [04:41<04:26,  5.03s/it]

  → Fetching Zion Williamson (4 seasons)...
  ✓ 85 games for Zion Williamson

 43%|███████████████████████████████████▋                                              | 40/92 [04:45<04:14,  4.90s/it]

  → Fetching Nikola Jokic (3 seasons)...
  ✗ Could not find NBA API ID for: Nikola Jokic
  ✗ No data for Nikola Jokic

 45%|████████████████████████████████████▌                                             | 41/92 [04:46<03:01,  3.55s/it]

  → Fetching Damian Lillard (4 seasons)...
  ✓ 321 games for Damian Lillard

 46%|█████████████████████████████████████▍                                            | 42/92 [04:51<03:23,  4.07s/it]

  → Fetching Klay Thompson (3 seasons)...
  ✓ 229 games for Klay Thompson

 47%|██████████████████████████████████████▎                                           | 43/92 [04:55<03:20,  4.08s/it]

  → Fetching Draymond Green (4 seasons)...
  ✓ 293 games for Draymond Green

 48%|███████████████████████████████████████▏                                          | 44/92 [05:58<17:18, 21.64s/it]

  → Fetching Anthony Davis (4 seasons)...
  ✓ 131 games for Anthony Davis

 49%|████████████████████████████████████████                                          | 45/92 [06:07<13:59, 17.86s/it]

  → Fetching Karl-Anthony Towns (4 seasons)...
  ✓ 323 games for Karl-Anthony Towns

 50%|█████████████████████████████████████████                                         | 46/92 [06:11<10:37, 13.86s/it]

  → Fetching Ben Simmons (4 seasons)...
  ✓ 275 games for Ben Simmons

 51%|█████████████████████████████████████████▉                                        | 47/92 [06:16<08:16, 11.03s/it]

  → Fetching Lonzo Ball (5 seasons)...
  ✓ 99 games for Lonzo Ball

 52%|██████████████████████████████████████████▊                                       | 48/92 [06:25<07:40, 10.46s/it]

  → Fetching De'Aaron Fox (3 seasons)...
  ✗ No data for De'Aaron Fox

 53%|███████████████████████████████████████████▋                                      | 49/92 [06:30<06:15,  8.74s/it]

  → Fetching Trae Young (4 seasons)...
  ✓ 280 games for Trae Young

 54%|████████████████████████████████████████████▌                                     | 50/92 [06:35<05:28,  7.81s/it]

  → Fetching Devin Booker (6 seasons)...
  ✓ 396 games for Devin Booker

 55%|█████████████████████████████████████████████▍                                    | 51/92 [07:17<12:16, 17.95s/it]

  → Fetching Bradley Beal (6 seasons)...
  ✓ 412 games for Bradley Beal

 57%|██████████████████████████████████████████████▎                                   | 52/92 [08:14<19:42, 29.57s/it]

  → Fetching Kemba Walker (3 seasons)...
  ✓ 216 games for Kemba Walker

 58%|███████████████████████████████████████████████▏                                  | 53/92 [08:17<14:08, 21.77s/it]

  → Fetching Donovan Mitchell (4 seasons)...
  ✓ 156 games for Donovan Mitchell

 59%|████████████████████████████████████████████████▏                                 | 54/92 [08:22<10:35, 16.72s/it]

  → Fetching Bam Adebayo (4 seasons)...
  ✓ 287 games for Bam Adebayo

 60%|█████████████████████████████████████████████████                                 | 55/92 [08:27<08:06, 13.16s/it]

  → Fetching Victor Oladipo (6 seasons)...
  ✓ 402 games for Victor Oladipo

 61%|█████████████████████████████████████████████████▉                                | 56/92 [08:34<06:42, 11.17s/it]

  → Fetching Domantas Sabonis (3 seasons)...
  ✓ 81 games for Domantas Sabonis

 62%|██████████████████████████████████████████████████▊                               | 57/92 [08:38<05:16,  9.05s/it]

  → Fetching CJ McCollum (3 seasons)...
  ✓ 222 games for CJ McCollum

 63%|███████████████████████████████████████████████████▋                              | 58/92 [08:41<04:10,  7.38s/it]

  → Fetching Hassan Whiteside (3 seasons)...
  ✓ 121 games for Hassan Whiteside

 64%|████████████████████████████████████████████████████▌                             | 59/92 [08:47<03:44,  6.79s/it]

  → Fetching Andre Drummond (3 seasons)...
  ✓ 244 games for Andre Drummond

 65%|█████████████████████████████████████████████████████▍                            | 60/92 [08:50<03:07,  5.85s/it]

  → Fetching Dennis Rodman (3 seasons)...
  ✓ 190 games for Dennis Rodman

 66%|██████████████████████████████████████████████████████▎                           | 61/92 [08:54<02:39,  5.16s/it]

  → Fetching Scottie Pippen (3 seasons)...
  ✓ 208 games for Scottie Pippen

 67%|███████████████████████████████████████████████████████▎                          | 62/92 [08:57<02:21,  4.72s/it]

  → Fetching Charles Barkley (6 seasons)...
  ✓ 408 games for Charles Barkley

 68%|████████████████████████████████████████████████████████▏                         | 63/92 [09:04<02:32,  5.26s/it]

  → Fetching Reggie Miller (6 seasons)...
  ✓ 454 games for Reggie Miller

 70%|█████████████████████████████████████████████████████████                         | 64/92 [09:13<02:57,  6.36s/it]

  → Fetching John Stockton (3 seasons)...
  ✓ 214 games for John Stockton

 71%|█████████████████████████████████████████████████████████▉                        | 65/92 [09:16<02:28,  5.49s/it]

  → Fetching Karl Malone (3 seasons)...
  ✓ 212 games for Karl Malone

 72%|██████████████████████████████████████████████████████████▊                       | 66/92 [09:20<02:07,  4.89s/it]

  → Fetching Grant Hill (3 seasons)...
  ✓ 92 games for Grant Hill

 73%|███████████████████████████████████████████████████████████▋                      | 67/92 [09:26<02:11,  5.28s/it]

  → Fetching Chris Webber (3 seasons)...
  ✓ 185 games for Chris Webber

 74%|████████████████████████████████████████████████████████████▌                     | 68/92 [09:30<01:57,  4.89s/it]

  → Fetching Anfernee Hardaway (3 seasons)...
  ✓ 218 games for Anfernee Hardaway

 75%|█████████████████████████████████████████████████████████████▌                    | 69/92 [09:33<01:39,  4.34s/it]

  → Fetching Kevin Johnson (3 seasons)...
  ✓ 194 games for Kevin Johnson

 76%|██████████████████████████████████████████████████████████████▍                   | 70/92 [09:37<01:30,  4.10s/it]

  → Fetching Hakeem Olajuwon (6 seasons)...
  ✓ 409 games for Hakeem Olajuwon

 77%|███████████████████████████████████████████████████████████████▎                  | 71/92 [09:43<01:43,  4.91s/it]

  → Fetching David Robinson (3 seasons)...
  ✓ 169 games for David Robinson

 78%|████████████████████████████████████████████████████████████████▏                 | 72/92 [09:47<01:30,  4.50s/it]

  → Fetching Alonzo Mourning (3 seasons)...
  ✓ 170 games for Alonzo Mourning

 79%|█████████████████████████████████████████████████████████████████                 | 73/92 [09:50<01:19,  4.20s/it]

  → Fetching Latrell Sprewell (3 seasons)...
  ✓ 133 games for Latrell Sprewell

 80%|█████████████████████████████████████████████████████████████████▉                | 74/92 [09:54<01:11,  3.99s/it]

  → Fetching Mitch Richmond (3 seasons)...
  ✓ 244 games for Mitch Richmond

 82%|██████████████████████████████████████████████████████████████████▊               | 75/92 [09:58<01:06,  3.91s/it]

  → Fetching Muggsy Bogues (3 seasons)...
  ✓ 161 games for Muggsy Bogues

 83%|███████████████████████████████████████████████████████████████████▋              | 76/92 [10:03<01:11,  4.47s/it]

  → Fetching Shawn Kemp (3 seasons)...
  ✓ 223 games for Shawn Kemp

 84%|████████████████████████████████████████████████████████████████████▋             | 77/92 [10:23<02:16,  9.12s/it]

  → Fetching Nick Van Exel (3 seasons)...
  ✓ 235 games for Nick Van Exel

 85%|█████████████████████████████████████████████████████████████████████▌            | 78/92 [10:27<01:45,  7.52s/it]

  → Fetching Glen Rice (3 seasons)...
  ✓ 240 games for Glen Rice

 86%|██████████████████████████████████████████████████████████████████████▍           | 79/92 [10:31<01:22,  6.34s/it]

  → Fetching Blake Griffin (3 seasons)...
  ✓ 228 games for Blake Griffin

 87%|███████████████████████████████████████████████████████████████████████▎          | 80/92 [10:34<01:05,  5.48s/it]

  → Fetching Jimmy Butler (6 seasons)...
  ✓ 217 games for Jimmy Butler

 88%|████████████████████████████████████████████████████████████████████████▏         | 81/92 [10:44<01:15,  6.83s/it]

  → Fetching Jayson Tatum (4 seasons)...
  ✓ 280 games for Jayson Tatum

 89%|█████████████████████████████████████████████████████████████████████████         | 82/92 [10:49<01:01,  6.15s/it]

  → Fetching Jaylen Brown (3 seasons)...
  ✓ 222 games for Jaylen Brown

 90%|█████████████████████████████████████████████████████████████████████████▉        | 83/92 [10:53<00:50,  5.63s/it]

  → Fetching Khris Middleton (6 seasons)...
  ✓ 397 games for Khris Middleton

 91%|██████████████████████████████████████████████████████████████████████████▊       | 84/92 [11:16<01:25, 10.70s/it]

  → Fetching Fred VanVleet (5 seasons)...
  ✓ 283 games for Fred VanVleet

 92%|███████████████████████████████████████████████████████████████████████████▊      | 85/92 [11:21<01:04,  9.15s/it]

  → Fetching Pascal Siakam (6 seasons)...
  ✓ 184 games for Pascal Siakam

 93%|████████████████████████████████████████████████████████████████████████████▋     | 86/92 [11:29<00:51,  8.59s/it]

  → Fetching Scottie Barnes (3 seasons)...
  ✓ 74 games for Scottie Barnes

 95%|█████████████████████████████████████████████████████████████████████████████▌    | 87/92 [11:34<00:38,  7.75s/it]

  → Fetching Cade Cunningham (3 seasons)...
  ✓ 64 games for Cade Cunningham

 96%|██████████████████████████████████████████████████████████████████████████████▍   | 88/92 [11:37<00:25,  6.34s/it]

  → Fetching Evan Mobley (3 seasons)...
  ✓ 148 games for Evan Mobley

 97%|███████████████████████████████████████████████████████████████████████████████▎  | 89/92 [11:41<00:16,  5.42s/it]

  → Fetching Jalen Green (3 seasons)...
  ✗ No data for Jalen Green

 98%|████████████████████████████████████████████████████████████████████████████████▏ | 90/92 [11:45<00:10,  5.12s/it]

  → Fetching Anthony Edwards (3 seasons)...
  ✗ No data for Anthony Edwards

 99%|█████████████████████████████████████████████████████████████████████████████████ | 91/92 [11:49<00:04,  4.74s/it]

  → Fetching LaMelo Ball (3 seasons)...
  ✗ No data for LaMelo Ball

100%|██████████████████████████████████████████████████████████████████████████████████| 92/92 [11:53<00:00,  7.76s/it]

Done fetching game logs.

In [3]:
# Verify game logs downloaded
import os
log_dir = '../data/raw/game_logs'
logs = os.listdir(log_dir)
print(f"Game logs fetched: {len(logs)}")
print("\n".join(sorted(logs)[:10]), "...")

Game logs fetched: 86
allen_iverson.csv
alonzo_mourning.csv
amare_stoudemire.csv
andre_drummond.csv
anfernee_hardaway.csv
anthony_davis.csv
bam_adebayo.csv
baron_davis.csv
ben_simmons.csv
blake_griffin.csv ...

In [4]:
# Fetch Genius lyrics metadata
# Requires GENIUS_API_KEY in .env
fetch_lyrics('../data/raw/mentions.csv')

Fetching lyrics for 160 songs...

  ↩ Drake — Forever (cached)
  ↩ Lil Wayne — Kobe Bryant (cached)
  ↩ Notorious B.I.G. — The What (cached)
  ↩ Jay-Z — Hovi Baby (cached)
  ↩ Kendrick Lamar — Backseat Freestyle (cached)
  ↩ Notorious B.I.G. — One More Chance (cached)
  ↩ Jay-Z — Public Service Announcement (cached)
  ↩ Jay-Z — D'Evils (cached)
  ↩ Ludacris — Saturday (Oooh Ooooh!) (cached)
  ↩ Common — The Food (cached)
  ↩ Kanye West — Champion (cached)
  ↩ Drake — Miss Me (cached)
  ↩ Jay-Z — Kingdom Come (cached)
  ↩ Travis Scott — Goosebumps (cached)
  ↩ Drake — God's Plan (cached)
  ↩ J. Cole — Apparently (cached)
  ↩ Pusha T — Santeria (cached)
  ↩ Drake — Champagne Poetry (cached)
  ↩ Young Thug — Ski (cached)
  ↩ Lil Wayne — Right Above It (cached)
  → Meek Mill — Cold Hearted II
  ✗ Not found on Genius
  ↩ Fabolous — Breathe (cached)
  ↩ Chance the Rapper — Paranoia (cached)
  ↩ E-40 — Tell Me When to Go (cached)
  ↩ Nas — Street Dreams (cached)
  ↩ Cam'ron — Dipset Anthem (cached)
  ↩ Lil Wayne — Mr. Carter (cached)
  ↩ Jay-Z — Encore (cached)
  ↩ Kanye West — Gone (cached)
  ↩ Jay-Z — Takeover (cached)
  ↩ Lil Wayne — A Milli (cached)
  ↩ Drake — Successful (cached)
  ↩ Jay-Z — Blueprint 2 (cached)
  ↩ Kanye West — All Falls Down (cached)
  ↩ Eminem — Lose Yourself (cached)
  ↩ Lil Wayne — Lollipop (cached)
  ↩ Drake — Energy (cached)
  ↩ Kendrick Lamar — HUMBLE. (cached)
  ↩ Meek Mill — Dangerous (cached)
  ↩ Drake — Laugh Now Cry Later (cached)
  ↩ J. Cole — p r i d e . i s . t h e . d e v i l (cached)
  ↩ Common — HER Love (cached)
  ↩ Drake — Trophies (cached)
  ↩ Kendrick Lamar — DNA. (cached)
  ↩ Drake — Forever (cached)
  ↩ Migos — Bad and Boujee (cached)
  ↩ Meek Mill — Going Bad (cached)
  ↩ Drake — God's Plan (cached)
  ↩ Kendrick Lamar — Alright (cached)
  ↩ Lil Baby — The Bigger Picture (cached)
  ↩ Drake — TSU (cached)
  ↩ J. Cole — Fire Squad (cached)
  ↩ Drake — Know Yourself (cached)
  ↩ Jay-Z — Smile (cached)
  ↩ Rick Ross — BIG TYME (cached)
  ↩ Future — Mask Off (cached)
  ↩ 2 Chainz — Momma I Hit a Lick (cached)
  ↩ Chance the Rapper — Blessings (cached)
  ↩ Rick Ross — Sanctified (cached)
  ↩ Big Sean — One Man Can Change the World (cached)
  ↩ Notorious B.I.G. — Big Poppa (cached)
  ↩ Jay-Z — Song Cry (cached)
  ↩ Ice Cube — Check Yo Self (cached)
  ↩ Jay-Z — 99 Problems (cached)
  ↩ Dr. Dre — The Next Episode (cached)
  ↩ Dr. Dre — Still D.R.E. (cached)
  ↩ Outkast — Ms. Jackson (cached)
  ↩ DMX — Ruff Ryders Anthem (cached)
  ↩ Tupac — Picture Me Rollin (cached)
  ↩ Ice Cube — It Was a Good Day (cached)
  ↩ Notorious B.I.G. — Juicy (cached)
  ↩ Tupac — California Love (cached)
  ↩ Jay-Z — Can I Get A... (cached)
  ↩ Nas — Hate Me Now (cached)
  ↩ Snoop Dogg — Gin and Juice (cached)
  ↩ Too Short — Gettin It (cached)
  ↩ Method Man — All I Need (cached)
  ↩ Sir Mix-a-Lot — Baby Got Back (cached)
  ↩ Snoop Dogg — Murder Was the Case (cached)
  ↩ 2Pac — How Do U Want It (cached)
  ↩ Jay-Z — Crown (cached)
  ↩ Drake — The Language (cached)
  ↩ Jay-Z — Dirt Off Your Shoulder (cached)
  ↩ Lil Wayne — Got Money (cached)
  ↩ Jay-Z — Empire State of Mind (cached)
  ↩ Kendrick Lamar — Swimming Pools (cached)
  ↩ Kanye West — Gorgeous (cached)
  ↩ Meek Mill — Rosé Red (cached)
  ↩ J. Cole — Love Yourz (cached)
  ↩ Drake — In My Feelings (cached)
  ↩ Meek Mill — Ima Boss (cached)
  ↩ Drake — What's Next (cached)
  ↩ J. Cole — KOD (cached)
  ↩ Big Sean — Bounce Back (cached)
  ↩ Drake — Chicago Freestyle (cached)
  ↩ Drake — From Time (cached)
  ↩ Lil Baby — Days Of Our Lives (cached)
  ↩ Drake — Fair Trade (cached)
  ↩ J. Cole — let go my hand (cached)
  ↩ Pusha T — Diet Coke (cached)
  ↩ Travis Scott — ESCAPE PLAN (cached)
  ↩ Drake — TSU (cached)
  ↩ Young Thug — Digits (cached)
  ↩ Jay-Z — Otis (cached)
  ↩ Eminem — Without Me (cached)
  ↩ Jay-Z — Song Cry (cached)
  ↩ Nas — Made You Look (cached)
  ↩ Jay-Z — U Don't Know (cached)
  ↩ J. Cole — Love Yourz (cached)
  ↩ Drake — Nonstop (cached)
  → Jay-Z — Open Letter
  ✓ Found — https://genius.com/Jay-z-open-letter-lyrics
  → J. Cole — January 28th
  ✓ Found — https://genius.com/J-cole-january-28th-lyrics
  ↩ Nas — Made You Look (cached)
  → Kendrick Lamar — Poetic Justice
  ✓ Found — https://genius.com/Kendrick-lamar-poetic-justice-lyrics
  → Meek Mill — Cold Hearted II
  ✗ Not found on Genius
  ↩ Drake — Nonstop (cached)
  → J. Cole — She Knows
  ✓ Found — https://genius.com/J-cole-she-knows-lyrics
  ↩ Kendrick Lamar — DNA. (cached)
  ↩ Drake — Laugh Now Cry Later (cached)
  ↩ Drake — Champagne Poetry (cached)
  ↩ Drake — What's Next (cached)
  → J. Cole — applying pressure
  ✓ Found — https://genius.com/Dw-destroyer-stacks-up-lyrics
  ↩ Kendrick Lamar — Swimming Pools (cached)
  → J. Cole — ATM
  ✓ Found — https://genius.com/J-cole-atm-lyrics
  → J. Cole — FRIENDS
  ✓ Found — https://genius.com/J-cole-friends-lyrics
  → Drake — Greece
  ✓ Found — https://genius.com/Dj-khaled-greece-lyrics
  → Kendrick Lamar — N95
  ✓ Found — https://genius.com/Kendrick-lamar-n95-lyrics
  → Kendrick Lamar — Rich Spirit
  ✓ Found — https://genius.com/Kendrick-lamar-rich-spirit-lyrics
  ↩ Drake — Fair Trade (cached)
  → J. Cole — my.life
  ✓ Found — https://genius.com/Kelby-my-life-j-cole-remix-lyrics
  → DMX — What's My Name
  ✓ Found — https://genius.com/Dmx-whats-my-name-lyrics
  ↩ Dr. Dre — Still D.R.E. (cached)
  → Jay-Z — Heart of the City
  ✓ Found — https://genius.com/Jay-z-heart-of-the-city-aint-no-love-lyrics
  → Jay-Z — On to the Next One
  ✓ Found — https://genius.com/Jay-z-on-to-the-next-one-lyrics
  ↩ Kendrick Lamar — Swimming Pools (cached)
  → Rick Ross — Santorini Greece
  ✓ Found — https://genius.com/Rick-ross-santorini-greece-lyrics
  → Nas — One Love
  ✓ Found — https://genius.com/Nas-one-love-lyrics
  → Drake — Lord Knows
  ✓ Found — https://genius.com/Drake-lord-knows-lyrics
  ↩ Drake — God's Plan (cached)
  → Meek Mill — Trauma
  ✓ Found — https://genius.com/Meek-mill-trauma-lyrics
  ↩ Drake — God's Plan (cached)
  ↩ Drake — Nonstop (cached)
  ↩ Drake — Laugh Now Cry Later (cached)
  → J. Cole — Heaven's EP
  ✓ Found — https://genius.com/Dreamville-and-j-cole-heavens-ep-lyrics
  → J. Cole — Snow On Tha Bluff
  ✓ Found — https://genius.com/J-cole-snow-on-tha-bluff-lyrics
  → Tupac — All About U
  ✓ Found — https://genius.com/2pac-all-about-u-lyrics
  → Nas — The Message
  ✓ Found — https://genius.com/Nas-the-message-lyrics
  ↩ Jay-Z — Can I Get A... (cached)
  ↩ Tupac — California Love (cached)
  → Jay-Z — Dead Presidents II
  ✓ Found — https://genius.com/Jay-z-dead-presidents-ii-lyrics
  → J. Cole — Let Nas Down
  ✓ Found — https://genius.com/J-cole-let-nas-down-lyrics
  ↩ Drake — Energy (cached)
  → Jay-Z — FML
  ✓ Found — https://genius.com/Modszy-joe-ghostproducer-lyrics
  → Kendrick Lamar — ELEMENT.
  ✓ Found — https://genius.com/Kendrick-lamar-element-lyrics
  → J. Cole — 4 Your Eyez Only
  ✓ Found — https://genius.com/J-cole-4-your-eyez-only-lyrics
  → J. Cole — Kevin's Heart
  ✓ Found — https://genius.com/J-cole-kevins-heart-lyrics
  ↩ Drake — Chicago Freestyle (cached)
  → Chance the Rapper — No Problem
  ✓ Found — https://genius.com/Chance-the-rapper-no-problem-lyrics
  ↩ Drake — Nonstop (cached)
  → Drake — Toosie Slide
  ✓ Found — https://genius.com/Drake-toosie-slide-lyrics

Saved lyrics metadata to D:\Codes\hip-hoop\notebooks\..\data\raw\lyrics_meta.csv

,mention_id,song,artist,lyric_snippet,full_lyrics_available,lyrics_length,url
0,1,Forever,Drake,That's why they call me Young Money LeBron Jam...,True,5531,https://genius.com/Drake-kanye-west-lil-wayne-...
1,2,Kobe Bryant,Lil Wayne,Call me Kobe Bryant cause I'm ballin' every night,True,4254,https://genius.com/Lil-wayne-kobe-bryant-lyrics
2,3,The What,Notorious B.I.G.,I'm catchin' bodies like Shaq catch alley-oops,True,3535,https://genius.com/The-notorious-big-the-what-...
3,4,Hovi Baby,Jay-Z,Flow butter smooth like Iverson crossover,True,3856,https://genius.com/Jay-z-hovi-baby-lyrics
4,5,Backseat Freestyle,Kendrick Lamar,Got K.D. numbers scoring every night,True,2881,https://genius.com/Kendrick-lamar-backseat-fre...
...,...,...,...,...,...,...,...
155,156,Kevin's Heart,J. Cole,Draymond talking loud but can you back it up w...,True,3152,https://genius.com/J-cole-kevins-heart-lyrics
156,157,Chicago Freestyle,Drake,Simmons can't shoot I'm taking every open thre...,True,2805,https://genius.com/Drake-and-giveon-chicago-fr...
157,158,No Problem,Chance the Rapper,Lonzo passing vision like Kidd out there runni...,True,4484,https://genius.com/Chance-the-rapper-no-proble...
158,159,Nonstop,Drake,Oladipo comeback story putting Indiana on his ...,True,3551,https://genius.com/Drake-nonstop-lyrics
159,160,Toosie Slide,Drake,Middleton steady like a rock gives you twenty ...,True,3169,https://genius.com/Drake-toosie-slide-lyrics

In [5]:
# Quick sanity check on a single game log
import pandas as pd
sample = pd.read_csv('../data/raw/game_logs/lebron_james.csv')
print(f"LeBron game log: {len(sample)} games")
print(sample[['GAME_DATE', 'PTS', 'AST', 'REB', 'SEASON']].head(10))

LeBron game log: 679 games
      GAME_DATE  PTS  AST  REB   SEASON
0  Apr 14, 2008   27    5    4  2007-08
1  Apr 13, 2008   13    7   11  2007-08
2  Apr 11, 2008   34    2    6  2007-08
3  Apr 09, 2008   33    8    7  2007-08
4  Apr 05, 2008   17    9    7  2007-08
5  Apr 03, 2008   33    4    5  2007-08
6  Apr 02, 2008   29    5    4  2007-08
7  Mar 30, 2008   26    9    9  2007-08
8  Mar 29, 2008   13    5    4  2007-08
9  Mar 26, 2008   21    8    3  2007-08